export const EnvKey = {
  SOCKET: "GIT_CREDENTIAL_FORWARDER_SOCKET",
  PORT: "GIT_CREDENTIAL_FORWARDER_PORT",
  SERVER: "GIT_CREDENTIAL_FORWARDER_SERVER",
  DEBUG: "GIT_CREDENTIAL_FORWARDER_DEBUG",
  GIT_PATH: "GIT_CREDENTIAL_FORWARDER_GIT_PATH"
}
